config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  #get 'welcome/index'
  root to: 'welcome#index'
  resources :coins  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type #, optional: true

    # métodos .map e .pluck

    # c = Coin.all
    # c.map { |coin| [coin.description, coin.acronym] } #Retorna descrição e sigla do array coin
    # c.map(&:description) #Retorna somente descrição e não aceita mais de uma
    # c.pluck(:description, :acronym) #Aceita retornar mais de um opção
    
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end
    
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  layout "adm" # criei adm.html.erb em layouts

  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[ new create edit update ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy

    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_mining_type_options
      # @mining_type_options = MiningType.all.map { |m| [ m.description, m.id ] }
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(
        :description,
        :acronym,
        :url_image,
        :mining_type_id
      )
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso de Ruby on Rails - [COOKIE]"
    session[:curso] = "Curso de Ruby on Rails - [SESSION]"
    
    @meu_nome = params[:nome]
    
    if @meu_nome.nil?
      @meu_nome = "Jesher Minelli Alves"
    end

    @curso = params[:curso]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def locale #Não usado, porém deixado para exemplo
        I18n.locale == :en ? "Inglês" : "Português do Brasil"
    end

    def date_br(data_us) #formatando hora na index da primeira pagina
        data_us.strftime("%d %B %Y")
    end
end

app/helpers/coins_helper.rb
module CoinsHelper
    
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control", placeholder:"Bitcoin" %>
  </div>

  <div class="form-group">
    <%= form.label :acronym %>
    <%= form.text_field :acronym, class:"form-control", placeholder:"BTC" %>
  </div>

  <div class="form-group">
    <%= form.label :url_image %>
    <%= form.text_field :url_image, class:"form-control", placeholder:"http://img.ur/bitcoin.png" %>
  </div><br>

  <div class="field">
    <%= form.label :mining_type_id %>
    <%= form.select("mining_type_id", @mining_type_options, { include_blank: 'Selecione...' }, class:"form-control") %>
  </div><br>
  
  <div class="actions">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

<br>

app/views/coins/edit.html.erb
<h1><%= t('editing.coin') %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.show'), @coin %> |
<%= link_to t('links.back'), coins_path %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= Coin.model_name.human(count: @coins.count) %></h1>
<p>Hoje <%= date_br(Date.today)%></p>
<table>
  <thead>
    <tr>
      <th><%= @coins.human_attribute_name(:description) %></th>
      <th><%= @coins.human_attribute_name(:acronym) %></th>
      <th><%= @coins.human_attribute_name(:url_image) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, alt: "Logo Moeda", width: 40 %> </td>
        <td><%= link_to t('links.show'), coin %></td>
        <td><%= link_to t('links.edit'), edit_coin_path(coin) %></td>
        <td><%= link_to t('links.delete'), coin, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.coin'), new_coin_path %> |
<%= link_to t('links.back'), root_path %>

app/views/coins/new.html.erb
<h1><%= t('new.coin') %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.back'), coins_path %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @coin.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong>Imagem:</strong><br><br>
  <%= image_tag @coin.url_image, width: 80 %>
</p>

<%= link_to t('links.edit'), edit_coin_path(@coin) %> |
<%= link_to t('links.back'), coins_path %>

app/views/layouts/adm.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>CABEÇALHO - ADM</h1>
    <%= yield %> <%# index.html.erb, edit.html.erb %>
    <h1>RODAPÉ - ADM</h1>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoWallet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <ul class="nav justify-content-end">
        <li>
          <%= link_to '[HOME]', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Português', root_path(locale: 'pt-BR'), class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'English', root_path(locale: 'en'), class:"nav-link" %>
        </li>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym %>
    <%= form.text_field :acronym %>
  </div><br>

  <div class="actions">
    <%= form.submit %>
  </div><br>
<% end %>

app/views/mining_types/edit.html.erb
<h1><%= t('editing.mining_type') %></h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to t('links.show'), @mining_type %> |
<%= link_to t('links.back'), mining_types_path %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= MiningType.model_name.human(count: @mining_types.count) %></h1>

<table>
  <thead>
    <tr>
      <th><%= @mining_types.human_attribute_name(:description) %></th>
      <th><%= @mining_types.human_attribute_name(:acronym) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type) %></td>
        <td><%= link_to t('links.delete'), mining_type, method: :delete, data: { confirm: t('messages.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new.mining_type'), new_mining_type_path %> |
<%= link_to t('links.back'), root_path %>

app/views/mining_types/new.html.erb
<h1>New Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to t('links.back'), mining_types_path %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong>Acronym:</strong>
  <%= @mining_type.acronym %>
</p>

<%= link_to t('links.edit'), edit_mining_type_path(@mining_type) %> |
<%= link_to t('links.back'), mining_types_path %>

app/views/welcome/_menu.html.erb
<%#= link_to "#{Coin.model_name.human}", coins_path, class:"btn btn-primary btn-lg", role:"button" %>
<%#= link_to "#{MiningType.model_name.human}", mining_types_path, class:"btn btn-primary btn-lg", role:"button" %>
<ul>
    <li>
        <h3><%= link_to "Moedas", coins_path%></h3>
    </li>
    <li> 
        <h3><%= link_to "Tipos de Mineração", mining_types_path%></h3>
    </li>
</ul>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t('welcome') %></h1>
  <h3 class="lead"><%= t('hello')%> eu me chamo <%= @meu_nome %></h3>
  <p> O idioma desta aplicação é <strong><%= t('current_locale') %></strong></p>
  <h3><strong>Hoje é </strong> <%= date_br(Date.today)%></h3>
  <hr class="my-4">
  <%= render "menu"%>
</div>